// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzuMrwfGUbSJc2t9YyJAAusuExSdVZkqg',
    appId: '1:536092486173:web:a27e17ac03fb121d4ab4f4',
    messagingSenderId: '536092486173',
    projectId: 'rakshak-money-mangager',
    authDomain: 'rakshak-money-mangager.firebaseapp.com',
    databaseURL: 'https://rakshak-money-mangager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rakshak-money-mangager.appspot.com',
    measurementId: 'G-6RNWKV3GWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNLhPEUYzItQ7CO8rdRgAvjnMuo_ZA8U',
    appId: '1:536092486173:android:e6a8fbd189148cd84ab4f4',
    messagingSenderId: '536092486173',
    projectId: 'rakshak-money-mangager',
    databaseURL: 'https://rakshak-money-mangager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rakshak-money-mangager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6nzeB1Ce4RnvdnvhiAR_xXU4sQBKi0_E',
    appId: '1:536092486173:ios:a32c1fc68d65b7fd4ab4f4',
    messagingSenderId: '536092486173',
    projectId: 'rakshak-money-mangager',
    databaseURL: 'https://rakshak-money-mangager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rakshak-money-mangager.appspot.com',
    iosBundleId: 'com.example.toDo',
  );
}
